spring:
  profiles:
    active: prod
  datasource:
    url: jdbc:hsqldb:hsql://localhost:9001/dev;ifexist=true

l2f:
    mail:
      address: l2f.you.from.future@gmail.com
      password: nonRealPassword
      host: smtp.googlemail.com
      port: 465