spring:
  profiles:
    active: prod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/letter2future?serverTimezone=GMT&useSSL=false
    username: root
    password: iseedeadpeople
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
l2f:
    link: http://localhost:8080
    verification:
      subject: Letter to future - email confirmation
    mail:
      address: l2f.you.from.future@gmail.com
      password: nonRealPassword
      host: smtp.googlemail.com
      port: 465